### ISSUE TITLE
Binder: spark initialization fails with: unexpected keyword argument 'auth_token'

### ISSUE THREAD

**Issue by pwrose** [sbl-sdsc/mmtf-pyspark#91]
When notebooks are launched in Binder, they now all show this error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-e05cafefe6a4> in <module>()
----> 1 spark = SparkSession.builder.master("local[4]").appName("Demo").getOrCreate()

/srv/conda/lib/python3.6/site-packages/pyspark/sql/session.py in getOrCreate(self)
    171                     for key, value in self._options.items():
    172                         sparkConf.set(key, value)
--> 173                     sc = SparkContext.getOrCreate(sparkConf)
    174                     # This SparkContext may be an existing one.
    175                     for key, value in self._options.items():

/srv/conda/lib/python3.6/site-packages/pyspark/context.py in getOrCreate(cls, conf)
    341         with SparkContext._lock:
    342             if SparkContext._active_spark_context is None:
--> 343                 SparkContext(conf=conf or SparkConf())
    344             return SparkContext._active_spark_context
    345 

/srv/conda/lib/python3.6/site-packages/pyspark/context.py in __init__(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls)
    113         """
    114         self._callsite = first_spark_call() or CallSite(None, None, None)
--> 115         SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
    116         try:
    117             self._do_init(master, appName, sparkHome, pyFiles, environment, batchSize, serializer,

/srv/conda/lib/python3.6/site-packages/pyspark/context.py in _ensure_initialized(cls, instance, gateway, conf)
    290         with SparkContext._lock:
    291             if not SparkContext._gateway:
--> 292                 SparkContext._gateway = gateway or launch_gateway(conf)
    293                 SparkContext._jvm = SparkContext._gateway.jvm
    294 

/srv/conda/lib/python3.6/site-packages/pyspark/java_gateway.py in launch_gateway(conf)
    118     gateway = JavaGateway(
    119         gateway_parameters=GatewayParameters(port=gateway_port, auth_token=gateway_secret,
--> 120                                              auto_convert=True))
    121 
    122     # Import the classes used by PySpark

TypeError: __init__() got an unexpected keyword argument 'auth_token'

**Comment by pwrose** [comment]
Fixed by #94

**Comment by pwrose** [comment]
Fixed by #94

**Comment by bkottapally** [comment]
I have the same error now. I am on Spark 2.3.1, but still face it. Any suggestions ?

**Comment by smomen** [comment]
@bkottapally try updating your `py4j` version, worked for me

**Comment by pwrose** [comment]
@bkottapally <https://github.com/bkottapally> please reopen this ticket if
you still see this error. I believe the upgrade to Spark 2.3.1 and
py4j to 0.10.7
fixed this issue.

**Comment by alexlusher** [comment]
@pwrose, I have py4j==0.10.7 and pyspark==2.3.1 running on my MacOS X High Sierra. I still experiene the following problem:

Traceback (most recent call last):
  File "/Users/al/Desktop/dev/Spark/etl/etl_job.py", line 237, in <module>
    main()
  File "/Users/al/Desktop/dev/Spark/etl/etl_job.py", line 56, in main
    files=['etl_config.json'])
  File "/Users/al/Desktop/dev/Spark/etl/etl_job.py", line 209, in start_spark
    spark_sess = spark_builder.getOrCreate()
  File "/usr/local/Cellar/apache-spark/2.3.1/libexec/python/lib/pyspark.zip/pyspark/sql/session.py", line 173, in getOrCreate
  File "/usr/local/Cellar/apache-spark/2.3.1/libexec/python/lib/pyspark.zip/pyspark/context.py", line 343, in getOrCreate
  File "/usr/local/Cellar/apache-spark/2.3.1/libexec/python/lib/pyspark.zip/pyspark/context.py", line 115, in __init__
  File "/usr/local/Cellar/apache-spark/2.3.1/libexec/python/lib/pyspark.zip/pyspark/context.py", line 292, in _ensure_initialized
  File "/usr/local/Cellar/apache-spark/2.3.1/libexec/python/lib/pyspark.zip/pyspark/java_gateway.py", line 120, in launch_gateway
TypeError: __init__() got an unexpected keyword argument 'auth_token'
2018-08-24 15:24:22 INFO  ShutdownHookManager:54 - Shutdown hook called 

All this happens when I try to run ETL example found here https://github.com/AlexIoannides/pyspark-example-project

Can you help?

Thanks!

**Comment by alexlusher** [comment]
Hi Peter,

I already did it.

Thanks,
Alex

**Comment by BigDataExplorers** [comment]
Hello All,
This issue was observed when you have multiple py4j dependencies added to the project. In my case, I had multiple egg/zip files added to my project and faced this issue.
